version: '3.6'
services:
  mysql:
    image: mysql:latest
    container_name: wplite-mysql
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    restart: always

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin:latest
    container_name: wplite-phpmyadmin
    restart: always
    ports:
      - 8180:80
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}

  wordpress:
    depends_on:
      - mysql
      - phpmyadmin
    image: wordpress:latest
    container_name: wplite-wordpress
    volumes:
      - ./theme:/var/www/html/wp-content/themes/wplite
    environment:
      - WORDPRESS_DB_NAME=${DB_NAME}
      - WORDPRESS_DB_HOST=${DB_HOST}
      - WORDPRESS_DB_USER=${DB_USER}
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
      - WORDPRESS_TABLE_PREFIX=${WP_TABLE_PREFIX}
      - WORDPRESS_DEBUG=${WP_DEBUG}
    restart: always
    ports:
      - 8080:80

volumes:
  mysql_data: {}
